#!/usr/bin/env bash
cd MEXECO99
echo -e "\e[33m                             __  __   ______ _  ___ ____ _  __   ___\e[0m"
echo -e "\e[33m                            |  \/  | / ____|\\  //   ||  | |/ / / _ \\e[0m"
echo -e "\e[33m                            | |\/| | /|  _|  \\//    ||  |   / | | | |\e[0m"
echo -e "\e[33m                            | |  | | \| |___ //\\    ||  | . \ | |_| |\e[0m"
echo -e "\e[33m                            |_|  |_| \_____|//  \\  ____ |_|\_\ \___/\e[0m"
while(true) do
lua start.lua 
done
